#!/usr/bin/env bash
# shellcheck shell=bash
set -euo pipefail

## Silently fall back to "plain" SSH, if:
## - Hashcolor is not found;
## - `ssh` is a part of a pipe command;
## - There are I/O redirections in place.
if ! type hashcolor &>/dev/null || ! [[ -t 0 && -t 1 && -t 2 ]]; then
   exec ssh "${@}"
fi

set_colors() {
    local _fg="${1}" _bg="${2}"
    if [[ "${TERM_PROGRAM}" == 'iTerm.app' ]]; then
        echo -e "\033]1337;SetColors=fg=rgb:${_fg}\033\\\033]1337;SetColors=bg=rgb:${_bg}\033\\"
    else
        echo -ne "\033]10;#${_fg}\007\033]11;#${_bg}\007"
    fi
}

## Set your FG/BG colors here:
DEFAULT_BG="000000"
DEFAULT_FG="EAEAEA"
SSH_OPTIONS=(
    -o "PermitLocalCommand=true"
    -o "LocalCommand=hashcolor %C"
)
## Check if we're being called from within the shell:
PARENT_COMMAND="$(ps -o comm= $PPID)"
if [[ "${PARENT_COMMAND}" =~ sh ]]; then
    ssh "${SSH_OPTIONS[@]}" "${@}"
    ## Capture SSH exit code here, to use it as our own later:
    SSH_EC="$?"
    ## Reset terminal colors to defaults:
    set_colors "${DEFAULT_FG}" "${DEFAULT_BG}"
    exit "${SSH_EC}"
else
    exec ssh "${SSH_OPTIONS[@]}" "${@}"
fi
